### ISSUE TITLE
How to Run this..!!

### ISSUE THREAD

**Issue by LK-98** [deepeshdm/Phishing-Attack-Domain-Detection#1]
Not Raising an Issue.
Just Want to know how to run.
After running pip Req. what is the procedure..?

**Comment by deepeshdm** [comment]
Once you have installed all the required dependencies,just import to get_prediction function from API.py and pass it the required arguments. Here's an example code.

```
from API import get_prediction

#path to trained model
model_path = r"/models/Malicious_URL_Prediction.h5"

#input url
url = "www.tesla.com/"

#returns probability of url being malicious
prediction = get_prediction(url,model_path)
print(prediction)

```

**Comment by deepeshdm** [comment]
Tell me if this works or you find any errors.
